### PR TITLE
New phrases precompile step

### PR DESCRIPTION
**Pull request by dcocchia**
New build step for building translation/phrase files for internationalization

@kwent looks like you're the only other one to have touched this, so seems worth mentioning to you  in case we're crazy :)

cc @ptrln

### CODE REVIEW

**Comment by kwent** [comment]
@dcocchia 

Cool you can try it out by modifying https://github.com/instacart/carrot/blob/master/customers/instacart/.buildpacks to

```
https://github.com/instacart/heroku-buildpack-ruby.git#add_translations_step
https://github.com/instacart/heroku-buildpack-nodejs.git#instacart
```

**Comment by dcocchia** [comment]
Gave it a shot last night and seemed good. :D

**Comment by josephgrossberg** [comment]
Hi @kwent @ptrln @dcocchia . I hope you're all doing well!

I left Instacart over two years ago, so I was surprised to see an email notification about this PR.

Please remove my access to this repo, and make sure your private github stuff is restricted to current employees and contractors.

Thanks!

**Comment by kwent** [comment]
@josephgrossberg Sorry for the noise but this repo is public ... You can `unwatch`the repo to not get any notifications anymore.

Regards

**Comment by josephgrossberg** [comment]
Ah, TY for clarifying! Glad it was not a security issue. 👍 

Sorry for the false alarm!

**Pull request merged**
